server:
  address: "127.0.0.1"
  port: 8080

github:
  v3_api_url: "https://api.github.com/"
  app:
    integration_id: 0
    webhook_secret: "some-webhook-secret"
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      something_foobar
      -----END RSA PRIVATE KEY-----

app_configuration:
  pull_request_preamble: "I am echo bot."
